### PR TITLE
Add FUNDING.yml

### PR DESCRIPTION
**Pull request by TroyKomodo**
## Proposed changes

Recently we got accepted for GitHub sponsors and OpenCollective.

So this PR aims to add those links to our repo.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/ScuffleTV/scuffle/blob/main/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Comments

CI is broken due to #55

### CODE REVIEW

**Review by mmattbtw — APPROVED** [review]
curious if this could be put in the root .github repo and applies to all

**Review by SputNikPlop — APPROVED** [review]
LGTM

**Comment by TroyKomodo** [comment]
> curious if this could be put in the root .github repo and applies to all

Lets try it

**Comment by TroyKomodo** [comment]
completed by https://github.com/ScuffleTV/.github/commit/cd84dbd8c4122e5d40fbdbdece1a397a282d67b1

**Pull request closed without merging**
