### PR TITLE
Implementation of SECURITY.md

### LINKED ISSUE #17: add Security policy

### PR DESCRIPTION
**Pull request by 4w3Official**
## Proposed changes

Security vulnerability reporting instructions for Scuffle

## Types of changes

What types of changes does your code introduce to Scuffle?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/ScuffleTV/scuffle/blob/main/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

E-Mail [security@scuffle.tv](mailto:security@scuffle.tv) needs to be set up
___
Closes #17

### CODE REVIEW

**Review by treuks — APPROVED** [review]

**Comment by SongoMen** [comment]
Would be cool if we reward those people somehow for example mentioning them somewhere in the repo.

**Comment by treuks** [comment]
reward = badge 
image

**Comment by 4w3Official** [comment]
Sounds like an interesting idea.... @TroyKomodo what do you think?

**Comment by mmattbtw** [comment]
you should add "Closes #17 " to your PR description to link the issue to the pr :-)

**Comment by TroyKomodo** [comment]
seems good!

**Review by TroyKomodo — APPROVED** [review]

**Pull request merged**
