### PR TITLE
chore: switch to mask

### PR DESCRIPTION
**Pull request by TroyKomodo**
## Proposed changes

Switch to mask as the task runner
Added missing ignore for MacOS + yarn log files.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/ScuffleTV/scuffle/blob/main/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by mmattbtw — APPROVED** [review]
seems good

**Review by SputNikPlop — APPROVED** [review]
LGTM

**Review by treuks — APPROVED** [review]
Works fine on my machine

**Comment by IS2511** [comment]
This was actually merged, see 606624d17ca39d1d7eb8247801b05f18b2db9dc4. For some reason this PR broke.

**Pull request closed without merging**
